[package]
name = "string_art_gui_web_worker"
version = "0.1.0"
edition = "2024"

[dependencies]
string_art_gui_common = { path = "../string_art_gui_common", features = [
    "serde",
] }
gloo-timers = { version = "^0.3", features = ["futures"] }
gloo-worker = { version = "^0.5", features = ["futures"] }
futures = { version = "^0.3" }
