[package]
name = "string_art"
version = "0.1.0"
edition = "2024"


[dependencies]
#string_art_sync = { path = "./string_art_sync", default-features = false }
string_art_geometry = { path = "./string_art_geometry", default-features = false }
string_art_color = { path = "./string_art_color", default-features = false}
string_art_math = { path = "./string_art_math" }
string_art_grid = { path = "string_art_grid" }
num-traits = { workspace = true }
derive_more = { workspace = true }
thiserror = { workspace = true }
fixed = "^1.29"

# Optional
## Feature "image"
image = { workspace = true, optional = true }

## Feature "serde"
serde = { workspace = true, optional = true }

## Feature "rayon"
rayon = { version = "^1.10", optional = true }
num_cpus = { version = "^1.16", optional = true }

[features]
default = ["image", "rayon"]
image = ["dep:image", "string_art_color/image"]
serde = ["dep:serde", "string_art_geometry/serde"]
rayon = ["dep:rayon", "num_cpus"]
