[package]
name = "string_art_ui"
version = "0.1.0"
edition = "2021"

[dependencies]
string_art = { path = "../string_art" }
eframe = "0.30.0"
egui = "0.30.0"
rfd = "0.15.2"
rayon = { workspace = true }
thiserror = { workspace = true }
image = { workspace = true }
svg = { workspace = true }
num-traits = { workspace = true }
parking_lot = "0.12.3"
open = "5.3.2"

[package.metadata.windows]
subsystem = "windows"
