/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_step_free: (a: number, b: number) => void;
export const __wbg_get_step_color: (a: number) => number;
export const __wbg_set_step_color: (a: number, b: number) => void;
export const __wbg_get_step_segment: (a: number) => number;
export const __wbg_set_step_segment: (a: number, b: number) => void;
export const __wbg_get_step_nail: (a: number) => number;
export const __wbg_set_step_nail: (a: number, b: number) => void;
export const __wbg_get_step_link: (a: number) => number;
export const __wbg_set_step_link: (a: number, b: number) => void;
export const __wbg_segment_free: (a: number, b: number) => void;
export const segment_start: (a: number) => number;
export const segment_end: (a: number) => number;
export const __wbg_point_free: (a: number, b: number) => void;
export const point_x: (a: number) => number;
export const point_y: (a: number) => number;
export const __wbg_computation_free: (a: number, b: number) => void;
export const computation_next: (a: number) => number;
export const __wbg_wasmerror_free: (a: number, b: number) => void;
export const __wbg_get_wasmerror_message: (a: number) => [number, number];
export const __wbg_set_wasmerror_message: (a: number, b: number, c: number) => void;
export const __wbg_settings_free: (a: number, b: number) => void;
export const __wbg_get_settings_decay: (a: number) => number;
export const __wbg_set_settings_decay: (a: number, b: number) => void;
export const settings_new: () => number;
export const settings_minNailDistance: (a: number) => number;
export const settings_set_minNailDistance: (a: number, b: number) => void;
export const settings_nailCount: (a: number) => number;
export const settings_set_nailCount: (a: number, b: number) => void;
export const settings_circularNailRadius: (a: number) => number;
export const settings_set_circularNailRadius: (a: number, b: number) => void;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_start: () => void;
